### ISSUE TITLE
Unable to process SMPL sequence + BSM model using current AddBiomechanics

### ISSUE THREAD

**Issue by yunhanwang1105** [keenon/AddBiomechanics#263]
Hi. Thank you for building up this platform. 

I am following the instructions from [SKEL](https://github.com/MarilynKeller/SMPL2AddBiomechanics) to generate b3d files from SMPL sequence + BSM model using the current AddBiomechanics platform. However, I encountered an error `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp53dq25zt/optimized_scale_and_markers.osim'`. I will attach the full error message in the end.

To my knowledge, SKEL was said to use the [development version of AddBiomechanics](https://dev.addbiomechanics.org/). But from what I see, the dev version only supports uploading datasets. 

May I kindly ask how can I mitigate this issue with the current AddBiomechanics? Thank you for your support.
Best.

```
Running lowpass filter
ERROR: Unwrapped joint pose is out of bounds at timestep 1185 of 2000. This means that we are trying to lowpass filter a joint angle that has wrapped around (for example, from 2PI back to 0, or from PI to -PI), and in "unwrapping" the joint angle to be continuous with the previous angle has caused it to go past the bound. Error joints are ['pelvis_tilt']
Writing OpenSim results
Writing the OpenSim result files...
Adjusting marker locations on scaled OpenSim file
Scaling OpenSim files: cd /tmp/tmp53dq25zt/ && opensim-cmd run-tool /tmp/tmp53dq25zt/rescaling_setup.xml
[info] Preparing to run ScaleTool.
[info] Processing subject optimized_scale_and_markers...
[info] Step 1: Loading generic model
[info] Updating Model file from 40000 to latest format...
[info] Loaded model FullBodyModel_MuscleActuatedLowerLimb_TorqueActuatedUpperBody from file /tmp/tmp53dq25zt/unscaled_but_with_optimized_markers.osim
[warning] Couldn't find file 'sacrum.vtp'.
[warning] Couldn't find file 'r_femur.vtp'.
[warning] Couldn't find file 'r_fibula.vtp'.
[warning] Couldn't find file 'r_patella.vtp'.
[warning] Couldn't find file 'r_talus.vtp'.
[warning] Couldn't find file 'r_foot.vtp'.
[warning] Couldn't find file 'r_bofoot.vtp'.
[warning] Couldn't find file 'l_femur.vtp'.
[warning] Couldn't find file 'l_fibula.vtp'.
[warning] Couldn't find file 'l_patella.vtp'.
[warning] Couldn't find file 'l_talus.vtp'.
[warning] Couldn't find file 'l_foot.vtp'.
[warning] Couldn't find file 'l_bofoot.vtp'.
[warning] Couldn't find file 'cervical_spine.vtp'.
[warning] Couldn't find file 'lumbar_spine.vtp'.
[warning] Couldn't find file 'thorax.vtp'.
[warning] Couldn't find file 'scapula.vtp'.
[warning] Couldn't find file 'scapula_l.vtp'.
[warning] Couldn't find file 'humerus.vtp'.
[warning] Couldn't find file 'humerus_l.vtp'.
[warning] Couldn't find file 'ulna.vtp'.
[warning] Couldn't find file 'ulna_l.vtp'.
[warning] Couldn't find file 'radius.vtp'.
[warning] Couldn't find file 'radius_l.vtp'.
[warning] Couldn't find file 'lunate.vtp'.
[warning] Couldn't find file 'lunate.vtp'.
[warning] Couldn't find file 'lunate_l.vtp'.
[error] Failed to connect Socket 'parent_frame' of type PhysicalFrame (details: Component 'BLTI' could not find 'tibia_l' of type PhysicalFrame. Make sure a component exists at this path and that it is of the correct type.
	Thrown at Component.h:770 in getComponent().).
	In Object 'BLTI' of type Marker.
	Thrown at Component.cpp:310 in finalizeConnections().
[error] Unable to load the generic model or marker set file.
[error] ScaleTool: No model specified.
[error] ScaleTool: No model specified.
Traceback (most recent call last):
  File "/app/src/../../engine/src/engine.py", line 105, in <module>
    main()
  File "/app/src/../../engine/src/engine.py", line 84, in main
    subject.write_opensim_results(path + output_name,
  File "/engine/src/subject.py", line 1017, in write_opensim_results
    self.scale_osim(
  File "/engine/src/subject.py", line 978, in scale_osim
    shutil.copyfile(tmpdirname + 'optimized_scale_and_markers.osim',
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp53dq25zt/optimized_scale_and_markers.osim'
exit: 1
```

**Comment by davidpagnon** [comment]
I'm interested, too. Maybe related to this? https://github.com/keenon/AddBiomechanics/issues/222

**Comment by Alex-Kupin** [comment]
The issue is the engine invokes opensim-cmd via a shell subprocess without using the full path.

You need to add the OpenSim bin directory to your PATH. Since Opensim is added to the python env, The CLI tool should be bundled with it.

Just make sure you add to path before running.

cd /home/akupin/AddBiomechanics/server/engine/src PATH="path_to/miniconda3/envs/yourenv/bin:$PATH"  path_to/miniconda3/envs/yourenv/bin/python engine.py data/dir
